        class Cliente:\n",
          def __init__(self, nome, email,plano):\n",
            self.nome = nome\n",
            self.email = email\n",
            self.lista_planos = ['Basico','Premiun']\n",
            if plano in self.lista_planos:\n",
              self.plano = plano\n",
        else:\n",
              raise Exception(\"Plano invalido\")\n",
            \n",
            def mudar_plano(self, nova_plano):\n",
              if novo_plano in self.lista_planos:\n",
                self.plano = novo_plano\n",
              else:\n",
                print(\"Plano invalido\")\n",
            def ver_filme(self, filme, plano_filme):\n",
              if self.plano == plano_filme:\n",
                print(f\"Ver filme {filme}\")\n",
              elif self.plano == \"premiun\":\n",
                print(f\"Ver filme {filme}\")\n",
              elif self.plano == \"basic\" and plano_filme == 'premiun':\n",
                print(\"Faça upgrade para premiun para ver esse filme.\")\n",
              else:\n",
                print(\"Plano invalido.\")        \n",

            #def ver_filme(self, filme):\n",
        cliente = Cliente(\"José Aldo\", \"abc@email.com\",\"Bx\" )\n",
      
        print(cliente.plano)\n",
        
        cliente.ver_filme(\"Fuga de Alcatraz\",\"Premiun\")\n",
        cliente.mudar_plano(\"Premiun\")\n",
        print(cliente.plano)"
